### ISSUE TITLE
Executing docker run give an error "docker: invalid reference format: repository name must be lowercase"

### ISSUE THREAD

**Issue by titusfx** [anibali/docker-pytorch#10]
I copy and paste ( several times ) the cmd of the readme which is:

```
docker run --rm -it --init \
  --runtime=nvidia \
  --ipc=host \
  --user="$(id -u):$(id -g)" \
  --volume=$PWD:/app \
  -e NVIDIA_VISIBLE_DEVICES=0 \
  anibali/pytorch python3 main.py
```

And I get the following error:

`docker: invalid reference format: repository name must be lowercase`

**Comment by anibali** [comment]
Try quoting the PWD part, like `--volume="$PWD:/app"`

**Comment by titusfx** [comment]
Yep, that definitely work:

```
docker run --rm -it --init \
  --runtime=nvidia \
  --ipc=host \
  --user="$(id -u):$(id -g)" \
  --volume="$PWD:/app" \
  -e NVIDIA_VISIBLE_DEVICES=0 \
  anibali/pytorch python3 main.py
```

That was because my path has space so $PWD will be a nonexistent folder, with " " it will get the full path

**Comment by anibali** [comment]
I thought that might be the case. Glad that it works for you now, I've updated the README for future users :)
