### ISSUE TITLE
Mount volume with user access

### ISSUE THREAD

**Issue by yunhan-zhao** [anibali/docker-pytorch#16]
Hi,

Thanks for the script! I have one question regarding the Volume command. If I define a `Volume /home/shared` in the Dockerfile, it seems like this volume will become root access only. Do you know how to mount a volume while preserving its user access?

**Comment by anibali** [comment]
This is really just a general Docker question, so I recommend just looking around for how other people handle this regardless of the specific image. Unfortunately there is no clean and easy way to solve it. The solution I use most often is to modify the Dockerfile by creating a user within that matches the UID on the host install. Also, make sure that you create the folder with correct permissions on the host first, before mounting it as a volume.

Check this out as an example of creating a non-root user in the Dockerfile: https://github.com/anibali/margipose/blob/master/Dockerfile#L17-L25

**Comment by yunhan-zhao** [comment]
Thanks for your suggestions! I'll try to match the UID first.
