### ISSUE TITLE
nvcc: command not found

### ISSUE THREAD

**Issue by seanyuner** [anibali/docker-pytorch#17]
Many thanks for this repo.

I pulled the cuda9.1 image, and when I ran some DNN model, it worked fine. But when I ran nvcc command, it showed:
`nvcc: command not found`
I debuged this issue following [here](https://askubuntu.com/questions/885610/nvcc-version-command-says-nvcc-is-not-installed), and I checked the /usr/local/cuda-9.1 directory, there was no bin sub-dir. 

So how could I run nvcc command in this image? looking forward to your reply.

**Comment by anibali** [comment]
These images are not built upon the development base images (deliberately, to keep them smaller). If you want to, you can build your own by copying https://github.com/anibali/docker-pytorch/blob/master/cuda-9.1/Dockerfile and changing the base image from:

```dockerfile
FROM nvidia/cuda:9.1-base-ubuntu16.04
```

to

```dockerfile
FROM nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04
```

**Comment by seanyuner** [comment]
ok! appreciate your fast reply, I got it.
