### ISSUE TITLE
how to install other python package ?

### ISSUE THREAD

**Issue by Hackerlil** [anibali/docker-pytorch#18]
such as :pandas

**Comment by josephrocca** [comment]
Also having the same problem. Did you work it out? I'm currently doing this sort of thing:
```python
import subprocess
subprocess.run(['bash','-c', "pip install ..."])
```
Would be happy to learn an easier way though! I don't know enough about Docker to know whether the repl can be escaped given that the docker file ends with `CMD ["python3"]`.

**Edit**: Repo maintainer recommends creating a separate dockerfile for this sort of thing I think: https://github.com/anibali/docker-pytorch/issues/12#issuecomment-482350607

**Comment by anibali** [comment]
@josephrocca You can always override the CMD by specifying a different command on the CLI when you run the container. For example, `docker run -it anibali/pytorch:cuda-10.1 bash` will run bash instead of python3.

**Comment by josephrocca** [comment]
Oh wow, I think I should go off now and do an intro-to-docker course. Thanks for that! And thanks for this very hand image :+1:
