### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by thomas-beznik** [anibali/docker-pytorch#21]
Hello,

I am trying to build a container from the Dockerfile for cuda-10.0; after downloading this file, I run the command "sudo docker build -t ai-api ." in the directory where the file is saved. I then get the following error: "Error response from daemon: failed to parse Dockerfile: Syntax error - can't find = in "RUN". Must be of the form: name=value". Any idea what the issue could be ?

Thanks!

**Comment by anibali** [comment]
Which version of Docker are you using?

I just tried building the image from scratch and it finished successfully with the following version:

```
$ docker --version
Docker version 19.03.5, build 633a0ea838
```
