### ISSUE TITLE
Usage of Dockerfile.template

### ISSUE THREAD

**Issue by username7171** [anibali/docker-pytorch#24]
May I know what is the usage of the file  "Dockerfile.template".  Seems that it is not used by any of the Dockerfile in all other directories.

**Comment by anibali** [comment]
I use that file as a template to generate all of the other Dockerfiles (using `update.sh`), which helps me keep them consistent with each other without having to edit each Dockerfile individually. It's only really intended to be used by myself and other contributors to the repo. For users wanting to modify a Dockerfile, each subdirectory is completely self-contained so you can just copy eg. `cuda-10.1/` somewhere and modify it however you like without worrying about the other files in the repo.
