### ISSUE TITLE
can we have a docker image with torch 1.4+ cuda 10.2 and ubuntu 16.04

### ISSUE THREAD

**Issue by ChunCun** [anibali/docker-pytorch#28]
Hi, I found it is really rare for a docker that is based on ubuntu16.04 and with cuda10.2. I really hope there's a version like this available. Thanks!

**Comment by anibali** [comment]
Ubuntu 16.04 is about to reach end-of-life (April 2021), so I won't be adding any more Docker images based on it. Feel free to fork the repository and create your own based on one of the existing Dockerfiles if you like.
