### ISSUE TITLE
Disable user prompt when building dockerfile

### ISSUE THREAD

**Issue by swigicat** [anibali/docker-pytorch#36]
When building from Dockerfile, there is a user prompt while installing openssh-server.

Can `ARG DEBIAN_FRONTEND=noninteractive` be added to the dockerfiles, after the `FROM` command?

**Comment by anibali** [comment]
On this matter I'd rather not change the behaviour of the base Ubuntu image. Users who are editing one of the Dockerfiles or deriving their own images can simply add this on a case-by-case basis depending on their needs. Thanks for the suggestion though.
