### ISSUE TITLE
why do we use miniconda with pytorch cuda image?

### ISSUE THREAD

**Issue by haiderasad** [anibali/docker-pytorch#39]
hi i am kind of stuck with docker gpu pytorch, basically my image is successfully built but on inference invocation when using cuda is gives out the following error
`ImportError: /root/.cache/torch_extensions/py38_cu113/fused/fused.so: cannot open shared object file: No such file or directory`

i am using nvidia/ image 

also i would like to ask why do we use miniconda with pytorch cuda image?

**Comment by anibali** [comment]
We use Conda because it makes it much easier to install third party packages, especially when they include binaries. The PyTorch developers seem to agree, as can be seen [on the PyTorch website](https://pytorch.org/get-started/locally/):
> Anaconda is our recommended package manager

**Comment by haiderasad** [comment]
Ok that explains a lot as i was also having troubles with loading cuda binaries from the runtime version of nvidia docker pytorch then it was solved by using the devel version , thanks
