### ISSUE TITLE
Can you support cuda-9.1 with pytorch 0.4.1?

### ISSUE THREAD

**Issue by John1231983** [anibali/docker-pytorch#4]
Thanks for sharing script to install pytorch with docker? Could you also share the dockerfile to install pytorch 0.4.1 in cuda 9-1 and cudnn 7.0? Thanks

**Comment by anibali** [comment]
Unfortunately these are the only Python 3.6 builds of PyTorch 0.4.1 provided by the pytorch conda repository (`conda search -c pytorch pytorch`):

```
pytorch                   0.4.1 py36_cuda8.0.61_cudnn7.1.2_1  pytorch             
pytorch                   0.4.1 py36_cuda9.0.176_cudnn7.1.2_1  pytorch             
pytorch                   0.4.1 py36_cuda9.2.148_cudnn7.1.4_1  pytorch 
```

If a PyTorch 0.4.1+CUDA 9.1 build eventually becomes available I'll use it in the image. In the meantime you'll have to use a different version of PyTorch/CUDA or possibly build PyTorch from source yourself.

**Comment by John1231983** [comment]
Great. How about docker for pytorch 4.1 and cuda 9.0 as second your output

**Comment by anibali** [comment]
I have added a new PyTorch 0.4.1 + CUDA 9.0 image and marked the `cuda-9.1` image as deprecated.

**Comment by John1231983** [comment]
Hello, for install nvidia-docker 2, why not insert the script in your docker script file. I have inserted based on the suggestion but it was the failure. I add after install opencv

```
 Add the package repositories
RUN curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey
RUN sudo apt-key add -distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
RUN curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list
RUN sudo tee /etc/apt/sources.list.d/nvidia-docker.list
RUN sudo apt-get update

# Install nvidia-docker2 and reload the Docker daemon configuration
RUN sudo apt-get install -y nvidia-docker2
RUN sudo pkill -SIGHUP dockerd

# Test nvidia-smi with the latest official CUDA image
RUN docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```

The error is 
```
E: Unable to locate package nvidia-docker2
The command '/bin/sh -c sudo apt-get install -y nvidia-docker2' returned a non-zero code: 100

```

**Comment by John1231983** [comment]
Ok it worked when I install from terminal instead of copy to docker file. Thanks

**Comment by anibali** [comment]
Yeah, `nvidia-docker2` needs to be installed on the host, not in the Docker image.
