### ISSUE TITLE
Images to work with for Google Cloud SDK

### ISSUE THREAD

**Issue by nahidalam** [anibali/docker-pytorch#40]
I was trying to use `anibali/pytorch:1.8.1-cuda11.1-ubuntu20.04` as the base image to create my own docker that needs to have `google-cloud-sdk`. But since google-cloud-sdk is not available in ubuntu20.04 yet, it will not work. Do you have any workaround for this? Maybe having an ubuntu 18 based image? Anything else?

Below a glimpse of my dockerfile.

```
ARG BASE_IMAGE=anibali/pytorch:1.8.1-cuda11.1-ubuntu20.04

FROM $BASE_IMAGE

......

RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk kubectl

```

**Comment by anibali** [comment]
It looks like Google does not use release-specific repositories anymore. Try this

```dockerfile
RUN export CLOUD_SDK_REPO="cloud-sdk" && \
...
```

Source: https://cloud.google.com/sdk/docs/install#deb
