### ISSUE TITLE
About the permissions of docekr images

### ISSUE THREAD

**Issue by StrongandSurvive** [anibali/docker-pytorch#41]
Hello, dear author, thank you for your work！ 
As a novice, I have encountered a problem that may be relatively low-level. Please give me some advice.
When I tried to build my own image based on your image: anibali/pytorch:1.10.0-nocuda, there was a problem with Dockerfile's RUN sudo mkdir-p / superBrain_face，error was reported as:

`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`
`The command '/bin/sh -c sudo mkdir -p /superBrain_face' returned a non-zero code: 1`

When I tried to execute the command `sudo su` in your image, I encountered the same problem. 
![sudo](https://user-images.githubusercontent.com/79584290/189287632-638cf103-d72f-46e9-b83c-be95bbb99e34.jpg)
Can you give me some advice? Thank You Very much~

**Comment by anibali** [comment]
It sounds like the issue might be specific to your environment. Do you have the same issue when running sudo with other Docker images?
