### ISSUE TITLE
ERROR: failed to solve -> 1.7.0-cuda11.0-ubuntu20.04

### ISSUE THREAD

**Issue by hankeceli** [anibali/docker-pytorch#46]
Hi, I am facing the following error, when I try to run specified dockerfile.

`ERROR: failed to solve: nvidia/cuda:11.0-base-ubuntu20.04: docker.io/nvidia/cuda:11.0-base-ubuntu20.04: not found`

**Comment by anibali** [comment]
Seems to be related to https://gitlab.com/nvidia/container-images/cuda/-/issues/188.

Try `11.0.3-base-ubuntu20.04` instead.
