### ISSUE TITLE
Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by hopewise** [anibali/docker-pytorch#5]
I tried to run the docker command, however, I got this error:

    docker: Error response from daemon: Unknown runtime specified nvidia

I am on Mac OS High Sierra, any idea?

**Comment by anibali** [comment]
It sounds like you don't have `nvidia-docker2` set up properly. You will need to get this working correctly before attempting to use `docker-pytorch`: https://github.com/NVIDIA/nvidia-docker

**Comment by anibali** [comment]
I should also add that getting GPU access from a Docker container when using a non-Linux host sounds complicated and is not something that I've done before. Perhaps this issue is of use to you: https://github.com/NVIDIA/nvidia-docker/issues/758.

**Comment by anibali** [comment]
Closing since this issue is beyond the `docker-pytorch` project.
